FROM gcc:11.4.0-bullseye as build-env
ENV MECAB_URL https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE
ENV MECAB_VERSION mecab-0.996
ENV MECAB_DIC_URL https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM
ENV MECAB_DIC_VERSION mecab-ipadic-2.7.0-20070801
RUN mkdir /work
RUN wget -q --no-check-certificate ${MECAB_URL} -O ${MECAB_VERSION}.tar.gz
RUN tar zxfv ${MECAB_VERSION}.tar.gz
WORKDIR ${MECAB_VERSION}/
RUN ./configure --with-charset=utf8
RUN make
RUN make install
RUN cp /usr/local/lib/libmecab.so.2 /lib/libmecab.so.2
WORKDIR /
RUN wget ${MECAB_DIC_URL} -O ${MECAB_DIC_VERSION}.tar.gz
RUN tar -xvf ${MECAB_DIC_VERSION}.tar.gz
WORKDIR ${MECAB_DIC_VERSION}/
RUN ./configure --with-charset=utf8
RUN make
RUN make install

FROM gcr.io/distroless/cc-debian11
COPY --from=build-env /usr/local /usr/local
COPY --from=build-env /usr/local/lib/libmecab.so.2 /lib/libmecab.so.2
