FROM ubuntu:20.04 as build-env
RUN apt-get update --allow-releaseinfo-change
RUN apt-get upgrade
RUN apt-get install -y mecab libmecab-dev mecab-ipadic
RUN which mecab

FROM gcr.io/distroless/cc-debian11:latest
COPY --from=build-env /usr/ /
